version: '3'

services:
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SERVICE_NAME=microservice-template
      - VERSION=1.0.0
      - PORT=8080
    depends_on:
      - redis
      - postgres
    
  redis:
    image: redis:3.2-alpine
    ports:
      - "6379:6379"
    
  postgres:
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_DB=microservice
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: